---
nsg_name: jumpbox_nsg

subnet:
  name: jumpbox_subnet
  address_prefix: "10.0.1.0/24"
  
publicip_name: lb_public_ip

loadbalancer_name: ssh_lb

nic: jumpbox_nic
ipaddress: "10.0.1.4"

vm_name: jumpbox
vm_size: Standard_A1
vm_admin_user: jumpbox
vm_sshkey_path: /home/"{{ vm_admin_user }}"/.ssh/authorized_keys
vm_sshkey_date: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCd8YZtCdoalPwKn7TxffAJ2h9D1XtfZwevRsGqg9mkx7O0rJOb3RpxMJ3+Sfw7DU7q/B7AbZ5X0EasAHyBpRoVTsYH8mK+/AmIL8F5E7ycQ2U6L2oP8AVAAeXyfZqyoLeTh2BNhQxziXm0sy3kB9ao1WddaouWnrb+rnNJgIJN+z8w6cyGEDUlJXlNbekxYl6k83amDfCdlzet5sXWhyac21uX1gxQE3J402iDINMZ3xtr3NyhdUkhYxxkK4mj55DmyihH+o8JdMwFLH1EXgbhXeihx7ac+7898gfPRwll/kKfDaIDq/stbNiWjYgdHMKcXwv3IIUDJ7CdMlFyjcH TN1K4UC@VWAPBJLVI0622
vm_image_offer: CentOS
vm_image_publisher: OpenLogic
vm_image_sku: '7.5'


