---
# Create network securit group
  - name: Create sonarqube app nsg 
    azure_rm_securitygroup:
      name: "{{ app_nsg_name }}"
      resource_group: "{{ resource_group_name }}"
      rules:
        - name: ssh
          protocol: Tcp
          source_port_range: "*"
          destination_port_range: 22
          source_address_prefix: "{{ jumpbox_ip }}"
          destination_address_prefix: "{{ app_subnet.address_prefix }}"
          access: Allow
          priority: 100
          direction: Inbound
        - name: allowAppGateway
          protocol: Tcp
          source_port_range: "*"
          destination_port_range: 9000
          source_address_prefix: "{{ appgw_ip }}"
          destination_address_prefix: "{{ app_subnet.address_prefix }}"
          access: Allow
          priority: 101
          direction: Inbound
        - name: denyall
          protocol: "*"
          source_port_range: "*"
          destination_port_range: "*"
          source_address_prefix: "*"
          destination_address_prefix: "*"
          access: Deny
          priority: 1001
          direction: Inbound  
    
  - name: Create sonarqube db nsg 
    azure_rm_securitygroup:
      name: "{{ db_nsg_name }}"
      resource_group: "{{ resource_group_name }}"
      rules:
        - name: ssh
          protocol: Tcp
          source_port_range: "*"
          destination_port_range: 22
          source_address_prefix: "{{ jumpbox_ip }}"
          destination_address_prefix: "{{ db_subnet.address_prefix }}"
          access: Allow
          priority: 100
          direction: Inbound
        - name: allowDB
          protocol: "*"
          source_port_range: "*"
          destination_port_range: 5432
          source_address_prefix: "{{ app_subnet.address_prefix }}"
          destination_address_prefix: "{{ db_subnet.address_prefix }}"
          access: Allow
          priority: 200
          direction: Inbound
        - name: denyall
          protocol: "*"
          source_port_range: "*"
          destination_port_range: "*"
          source_address_prefix: "*"
          destination_address_prefix: "*"
          access: Deny
          priority: 1001
          direction: Inbound
    
# Create app subnet
  - name: Create sonarqube app subnet
    azure_rm_subnet:
      name: "{{ app_subnet.name }}"
      resource_group: "{{ resource_group_name }}"
      address_prefix_cidr: "{{ app_subnet.address_prefix }}"
      virtual_network_name: "{{ vnet_name }}"
      security_group: "{{ app_nsg_name }}"
      
  - name: Create sonarqube db subnet
    azure_rm_subnet:
      name: "{{ db_subnet.name }}"
      resource_group: "{{ resource_group_name }}"
      address_prefix_cidr: "{{ db_subnet.address_prefix }}"
      virtual_network_name: "{{ vnet_name }}"
      security_group: "{{ db_nsg_name }}"

#Create network interface card
  - name: Create sonarqube app NIC
    azure_rm_networkinterface:
      name: "{{ app_nic }}"
      resource_group: "{{ resource_group_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ app_subnet.name }}"
      ip_configurations: 
        - name: sonarqube_ipconfig
          private_ip_address: "{{ app_ipaddress }}"
          private_ip_allocation_method: Static
          primary: yes
          load_balancer_backend_address_pools: 
            - name: "{{ loadbalancer_name }}"
              load_balancer: "{{ loadbalancer_bend_pool }}"
      create_with_security_group: no
      
  - name: Create sonarqube db NIC
    azure_rm_networkinterface:
      name: "{{ db_nic }}"
      resource_group: "{{ resource_group_name }}"
      virtual_network: "{{ vnet_name }}"
      subnet: "{{ db_subnet.name }}"
      ip_configurations: 
        - name: sonarqube_ipconfig
          private_ip_address: "{{ db_ipaddress }}"
          private_ip_allocation_method: Static
          primary: yes
      create_with_security_group: no
  
#Create VM
  - name: Create sonarqube app VM
    azure_rm_virtualmachine:
      name: "{{ app_vm_name }}"
      resource_group: "{{ resource_group_name }}"
      admin_username: "{{ app_vm_admin_user }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "{{ vm_sshkey_path }}"
          key_data: "{{ vm_sshkey_date }}"
      network_interfaces: "{{ app_nic }}"
      image:
        offer: "{{ vm_image_offer }}"
        publisher: "{{ vm_image_publisher }}"
        sku: "{{ vm_image_sku }}"
        version: latest
      vm_size: "{{ app_vm_size }}"
      managed_disk_type: Standard_LRS

  - name: Create sonarqube db VM
    azure_rm_virtualmachine:
      name: "{{ db_vm_name }}"
      resource_group: "{{ resource_group_name }}"
      admin_username: "{{ db_vm_admin_user }}"
      ssh_password_enabled: false
      ssh_public_keys:
        - path: "{{ vm_sshkey_path }}"
          key_data: "{{ vm_sshkey_date }}"
      network_interfaces: "{{ db_nic }}"
      image:
        offer: "{{ vm_image_offer }}"
        publisher: "{{ vm_image_publisher }}"
        sku: "{{ vm_image_sku }}"
        version: latest
      vm_size: "{{ db_vm_size }}"
      managed_disk_type: Standard_LRS
      data_disks:
        - lun: 0
          disk_size_gb: 160
          managed_disk_type: Premium_LRS
          caching: ReadWrite
  
















